import CssBaseline from '@mui/material/CssBaseline';
import GlobalStyles from '@mui/material/GlobalStyles';
import { getServerSession } from 'next-auth/next';

import { TopHeader } from '@/components/TopHeader';

import { authOptions } from '../api/auth/[...nextauth]/route';
import Provider from '../context/client-provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <Provider session={session}>
          <GlobalStyles
            styles={{ ul: { margin: 0, padding: 0, listStyle: 'none' } }}
          />
          <CssBaseline />
          <TopHeader />
          {children}
        </Provider>
      </body>
    </html>
  );
}
